"use strict";
const assert = require("node:assert/strict");
const { OPENINGS, TURNS, newGame, choose, lines } = require("./app.js");
assert.ok(OPENINGS.length >= 5);
assert.equal(TURNS.length, 6);
assert.deepEqual(TURNS.map((turn) => turn.lead), ["但是", "幸好", "但是", "幸好", "但是", "最後"]);
assert.ok(TURNS.every((turn) => turn.choices.length === 2 && turn.choices.every(Boolean)));
assert.equal(newGame(() => 0).opening, OPENINGS[0]);
assert.equal(newGame(() => .999).opening, OPENINGS.at(-1));
assert.throws(() => newGame(() => 1), RangeError);
let game = newGame(() => 0);
const first = choose(game, 1);
assert.equal(game.picks.length, 0, "choice should not mutate previous state");
assert.equal(first.picks[0], 1);
assert.throws(() => choose(game, 2), RangeError);
assert.throws(() => choose(game, -1), RangeError);
for (let i = 0; i < TURNS.length; i++) game = choose(game, i % 2);
assert.equal(lines(game).length, 7);
assert.equal(lines(game)[0], OPENINGS[0]);
assert.equal(lines(game)[1], `但是，${TURNS[0].choices[0]}`);
assert.throws(() => choose(game, 0), RangeError);
console.log("tiny-story-switch core tests: PASS");
